name = "Zero"
grammar = "zero"
path_suffixes = ["0"]
line_comments = ["// "]
block_comment = ["/*", "*/"]
tab_size = 4
hard_tabs = false

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "<", end = ">", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
]
