name = "Zero"
grammar = "zero"
path_suffixes = ["0"]
line_comments = ["// "]
block_comment = ["/* ", " */"]
tab_size = 4
hard_tabs = false
autoclose_before = ";:.,=}])>"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "<", end = ">", close = false, newline = false, not_in = ["string", "comment"] },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
]
