#ifndef ZERO_C_STD_SIG_H
#define ZERO_C_STD_SIG_H

#include <stdbool.h>
#include <stddef.h>

#define Z_STD_HELPER_MAX_ARGS 5
#define Z_STD_HELPER_MAX_ERRORS 4

typedef enum {
  Z_STD_HELPER_KIND_TABLE,
  Z_STD_HELPER_KIND_MEM_LEN,
  Z_STD_HELPER_KIND_MEM_GET,
  Z_STD_HELPER_KIND_MEM_EQL_BYTES,
  Z_STD_HELPER_KIND_MEM_COPY_ITEMS,
  Z_STD_HELPER_KIND_MEM_FILL_ITEMS,
  Z_STD_HELPER_KIND_MEM_CONTAINS,
  Z_STD_HELPER_KIND_MEM_IS_EMPTY,
  Z_STD_HELPER_KIND_MEM_SLICE,
  Z_STD_HELPER_KIND_COLLECTIONS_PUSH,
  Z_STD_HELPER_KIND_COLLECTIONS_APPEND,
  Z_STD_HELPER_KIND_COLLECTIONS_VIEW,
  Z_STD_HELPER_KIND_COLLECTIONS_LEN_STATE,
  Z_STD_HELPER_KIND_COLLECTIONS_LEN_USIZE,
  Z_STD_HELPER_KIND_COLLECTIONS_LEN_MAYBE_VALUE,
  Z_STD_HELPER_KIND_COLLECTIONS_LEN_VALUE,
  Z_STD_HELPER_KIND_COLLECTIONS_MUT_LEN_STATE,
  Z_STD_HELPER_KIND_COLLECTIONS_MUT_LEN_VALUE,
  Z_STD_HELPER_KIND_COLLECTIONS_LEN_INDEX,
  Z_STD_HELPER_KIND_COLLECTIONS_INSERT_AT,
  Z_STD_HELPER_KIND_COLLECTIONS_REPLACE_AT,
  Z_STD_HELPER_KIND_COLLECTIONS_SWAP_AT,
  Z_STD_HELPER_KIND_COLLECTIONS_MAP_CONTAINS,
  Z_STD_HELPER_KIND_COLLECTIONS_MAP_INDEX,
  Z_STD_HELPER_KIND_COLLECTIONS_MAP_GET,
  Z_STD_HELPER_KIND_COLLECTIONS_MAP_VALUES,
  Z_STD_HELPER_KIND_COLLECTIONS_MAP_STATE,
  Z_STD_HELPER_KIND_COLLECTIONS_MAP_TRUNCATE,
  Z_STD_HELPER_KIND_COLLECTIONS_MAP_PUT,
  Z_STD_HELPER_KIND_COLLECTIONS_MAP_REMOVE,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_SET_CONSTRUCTOR,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_SET_STATE,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_SET_VIEW,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_SET_VALUE,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_SET_MUT_VALUE,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_SET_TRUNCATE,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_DEQUE_CONSTRUCTOR,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_DEQUE_STATE,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_DEQUE_VIEW,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_DEQUE_VALUE,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_DEQUE_MUT_VALUE,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_DEQUE_POP,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_DEQUE_TRUNCATE,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_RING_BUFFER_CONSTRUCTOR,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_RING_BUFFER_STATE,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_RING_BUFFER_VALUE,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_RING_BUFFER_GET,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_RING_BUFFER_MUT_VALUE,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_RING_BUFFER_POP,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_RING_BUFFER_TRUNCATE,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_MAP_CONSTRUCTOR,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_MAP_STATE,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_MAP_VIEW,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_MAP_KEY,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_MAP_GET,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_MAP_PUT,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_MAP_REMOVE,
  Z_STD_HELPER_KIND_COLLECTIONS_FIXED_MAP_TRUNCATE,
  Z_STD_HELPER_KIND_SEARCH_INDEX,
  Z_STD_HELPER_KIND_MEM_ALLOC_BYTES,
  Z_STD_HELPER_KIND_MEM_BYTE_BUF,
  Z_STD_HELPER_KIND_FS_READ,
  Z_STD_HELPER_KIND_FS_READ_ALL,
  Z_STD_HELPER_KIND_FS_READ_ALL_OR_RAISE,
  Z_STD_HELPER_KIND_JSON_PARSE,
  Z_STD_HELPER_KIND_JSON_PARSE_BYTES,
  Z_STD_HELPER_KIND_HTTP_LISTEN,
  Z_STD_HELPER_KIND_UNKNOWN
} ZStdHelperKind;

typedef struct ZStdHelperInfo {
  const char *name;
  const char *return_type;
  int arg_count;
  const char *arg_types[Z_STD_HELPER_MAX_ARGS];
  const char *error_names[Z_STD_HELPER_MAX_ERRORS];
  const char *capability;
  const char *target_support;
  const char *allocation_behavior;
  bool emits_runtime_helper;
  ZStdHelperKind kind;
} ZStdHelperInfo;

extern const ZStdHelperInfo z_std_helpers[];

size_t z_std_helper_count(void);
const ZStdHelperInfo *z_std_helper_find(const char *name);
int z_std_helper_index(const char *name, size_t max_helpers);
ZStdHelperKind z_std_helper_kind(const ZStdHelperInfo *helper);
const char *z_std_helper_arg_type(const char *name, size_t index);
const char *z_std_helper_error_name(const ZStdHelperInfo *helper, size_t index);
bool z_std_helper_is_fallible(const ZStdHelperInfo *helper);
void z_std_helper_error_set_text(const ZStdHelperInfo *helper, char *buf, size_t cap);

#endif
