#include "std_sig.h"

#include <string.h>

const ZStdHelperInfo z_std_helpers[] = {
  {"std.args.len", "usize", 0, "args", "host", "borrows process argv", true},
  {"std.args.get", "Maybe<String>", 1, "args", "host", "borrows process argv", true},
  {"std.env.get", "Maybe<String>", 1, "env", "host", "borrows process environment", true},
  {"std.path.basename", "String", 1, "path", "target-neutral", "borrows input path", true},
  {"std.path.dirname", "String", 1, "path", "target-neutral", "borrows/static path view", true},
  {"std.path.extension", "String", 1, "path", "target-neutral", "borrows input path", true},
  {"std.path.join", "Maybe<String>", 3, "path", "target-neutral", "writes caller buffer", true},
  {"std.path.normalize", "Maybe<String>", 2, "path", "target-neutral", "writes caller buffer", true},
  {"std.path.relative", "Maybe<String>", 3, "path", "target-neutral", "writes caller buffer", true},
  {"std.io.bufferedReader", "BufferedReader", 1, "memory", "target-neutral", "uses caller buffer", true},
  {"std.io.bufferedWriter", "BufferedWriter", 1, "memory", "target-neutral", "uses caller buffer", true},
  {"std.io.readerCapacity", "usize", 1, "memory", "target-neutral", "no allocation", false},
  {"std.io.writerCapacity", "usize", 1, "memory", "target-neutral", "no allocation", false},
  {"std.io.copy", "usize", 2, "memory", "target-neutral", "writes caller buffer", true},
  {"std.codec.crc32", "u32", 1, "codec", "target-neutral", "no allocation", true},
  {"std.codec.crc32Bytes", "u32", 1, "codec", "target-neutral", "no allocation", true},
  {"std.codec.encodedVarintLen", "usize", 1, "codec", "target-neutral", "no allocation", true},
  {"std.codec.readU8", "u8", 1, "codec", "target-neutral", "little-endian byte read", true},
  {"std.codec.readU16", "u16", 1, "codec", "target-neutral", "little-endian byte read", true},
  {"std.codec.readU32", "u32", 1, "codec", "target-neutral", "little-endian byte read", true},
  {"std.codec.writeU16", "u32", 1, "codec", "target-neutral", "little-endian byte write primitive", true},
  {"std.codec.writeU32", "u32", 1, "codec", "target-neutral", "little-endian byte write primitive", true},
  {"std.codec.base64EncodedLen", "usize", 1, "codec", "target-neutral", "no allocation", true},
  {"std.codec.base64Encode", "Maybe<String>", 2, "codec", "target-neutral", "writes caller buffer", true},
  {"std.codec.hexEncode", "Maybe<String>", 2, "codec", "target-neutral", "writes caller buffer", true},
  {"std.codec.utf8Valid", "Bool", 1, "codec", "target-neutral", "no allocation", true},
  {"std.codec.urlEncode", "Maybe<String>", 2, "codec", "target-neutral", "writes caller buffer", true},
  {"std.mem.copy", "usize", 2, "memory", "target-neutral", "writes caller buffer", true},
  {"std.mem.fill", "usize", 2, "memory", "target-neutral", "writes caller buffer", true},
  {"std.mem.eql", "Bool", 2, "memory", "target-neutral", "no allocation", true},
  {"std.mem.span", "Span<u8>", 1, "memory", "target-neutral", "borrows input bytes", true},
  {"std.mem.len", "usize", 1, "memory", "target-neutral", "no allocation", false},
  {"std.mem.get", "Maybe<T>", 2, "memory", "target-neutral", "bounds-checked indexed read", false},
  {"std.mem.eqlBytes", "Bool", 2, "memory", "target-neutral", "no allocation", false},
  {"std.mem.nullAlloc", "NullAlloc", 0, "alloc", "target-neutral", "never allocates", true},
  {"std.mem.fixedBufAlloc", "FixedBufAlloc", 1, "alloc", "target-neutral", "uses caller buffer", true},
  {"std.mem.arena", "FixedBufAlloc", 1, "alloc", "target-neutral", "bulk allocation over caller buffer", true},
  {"std.mem.pageAlloc", "PageAlloc", 0, "alloc", "host", "explicit page allocator handle", false},
  {"std.mem.generalAlloc", "GeneralAlloc", 0, "alloc", "host", "explicit general allocator handle", false},
  {"std.mem.allocBytes", "Maybe<MutSpan<u8>>", 2, "alloc", "target-neutral", "uses explicit allocator only", true},
  {"std.mem.byteBuf", "Maybe<owned<ByteBuf>>", 2, "alloc", "target-neutral", "uses explicit allocator only", true},
  {"std.mem.vec", "Vec", 1, "memory", "target-neutral", "uses caller storage", true},
  {"std.mem.vecPush", "Bool", 2, "memory", "target-neutral", "writes caller storage", true},
  {"std.mem.vecLen", "usize", 1, "memory", "target-neutral", "no allocation", false},
  {"std.mem.vecCapacity", "usize", 1, "memory", "target-neutral", "no allocation", false},
  {"std.mem.bufBytes", "MutSpan<u8>", 1, "memory", "target-neutral", "borrows owned buffer", false},
  {"std.mem.bufLen", "usize", 1, "memory", "target-neutral", "no allocation", false},
  {"std.mem.reset", "Void", 1, "alloc", "target-neutral", "resets explicit allocator", true},
  {"std.mem.capacity", "usize", 1, "alloc", "target-neutral", "no allocation", false},
  {"std.mem.mapEmpty", "Map", 0, "memory", "target-neutral", "no allocation", false},
  {"std.mem.mapLen", "usize", 1, "memory", "target-neutral", "no allocation", false},
  {"std.mem.setEmpty", "Set", 0, "memory", "target-neutral", "no allocation", false},
  {"std.mem.setLen", "usize", 1, "memory", "target-neutral", "no allocation", false},
  {"std.parse.isAsciiDigit", "Bool", 1, "parse", "target-neutral", "no allocation", true},
  {"std.parse.isAsciiAlpha", "Bool", 1, "parse", "target-neutral", "no allocation", true},
  {"std.parse.isIdentifierStart", "Bool", 1, "parse", "target-neutral", "no allocation", true},
  {"std.parse.isWhitespace", "Bool", 1, "parse", "target-neutral", "no allocation", true},
  {"std.parse.scanDigits", "usize", 1, "parse", "target-neutral", "no allocation", true},
  {"std.parse.scanIdentifier", "usize", 1, "parse", "target-neutral", "no allocation", true},
  {"std.parse.parseU8", "Maybe<u8>", 1, "parse", "target-neutral", "no allocation", true},
  {"std.parse.parseU16", "Maybe<u16>", 1, "parse", "target-neutral", "no allocation", true},
  {"std.parse.parseU32", "Maybe<u32>", 1, "parse", "target-neutral", "no allocation", true},
  {"std.json.validate", "Bool", 1, "parse", "target-neutral", "no allocation", true},
  {"std.json.validateBytes", "Bool", 1, "parse", "target-neutral", "no allocation", true},
  {"std.json.parse", "Maybe<JsonDoc>", 2, "alloc", "target-neutral", "uses explicit allocator only", true},
  {"std.json.parseBytes", "Maybe<JsonDoc>", 2, "alloc", "target-neutral", "uses explicit allocator only", true},
  {"std.json.streamTokens", "usize", 1, "parse", "target-neutral", "streaming token count", true},
  {"std.json.streamTokensBytes", "usize", 1, "parse", "target-neutral", "streaming token count", true},
  {"std.json.writeString", "Maybe<String>", 2, "parse", "target-neutral", "writes caller buffer", true},
  {"std.json.decodeBoundary", "String", 0, "parse", "target-neutral", "typed decode boundary metadata", false},
  {"std.time.ms", "Duration", 1, "time", "target-neutral", "no allocation", true},
  {"std.time.seconds", "Duration", 1, "time", "target-neutral", "no allocation", true},
  {"std.time.add", "Duration", 2, "time", "target-neutral", "no allocation", true},
  {"std.time.monotonic", "Duration", 0, "time", "host", "no allocation", true},
  {"std.time.wallSeconds", "i64", 0, "time", "host", "no allocation", true},
  {"std.time.sub", "Duration", 2, "time", "target-neutral", "no allocation", true},
  {"std.time.asMsFloor", "i32", 1, "time", "target-neutral", "no allocation", true},
  {"std.time.min", "Duration", 2, "time", "target-neutral", "no allocation", true},
  {"std.time.max", "Duration", 2, "time", "target-neutral", "no allocation", true},
  {"std.time.lessThan", "Bool", 2, "time", "target-neutral", "no allocation", true},
  {"std.rand.seed", "RandSource", 1, "rand", "target-neutral", "deterministic test source", true},
  {"std.rand.nextU32", "u32", 1, "rand", "target-neutral", "updates explicit source", true},
  {"std.rand.entropyU32", "u32", 0, "rand", "host", "target entropy source", true},
  {"std.proc.spawn", "ProcStatus", 1, "proc", "host", "explicit process capability", true},
  {"std.proc.exitCode", "i32", 1, "proc", "host", "no allocation", false},
  {"std.crypto.hash32", "u32", 1, "codec", "target-neutral", "no allocation", true},
  {"std.crypto.hmac32", "u32", 2, "codec", "target-neutral", "no allocation", true},
  {"std.crypto.constantTimeEql", "Bool", 2, "memory", "target-neutral", "no allocation", true},
  {"std.crypto.secureRandomU32", "u32", 0, "rand", "host", "target entropy source", true},
  {"std.net.host", "Net", 0, "net", "host", "explicit network capability handle", false},
  {"std.net.address", "Address", 2, "net", "target-neutral", "no allocation", true},
  {"std.net.dnsName", "String", 1, "net", "target-neutral", "borrows address host", false},
  {"std.net.connect", "Maybe<Conn>", 2, "net", "host", "no allocation; returns unopened bootstrap handle", true},
  {"std.net.listen", "Maybe<Listener>", 2, "net", "host", "no allocation; returns unopened bootstrap handle", true},
  {"std.net.withTimeout", "Address", 2, "net", "target-neutral", "no allocation", true},
  {"std.http.parseMethod", "HttpMethod", 1, "parse", "target-neutral", "no allocation", true},
  {"std.http.client", "HttpClient", 1, "net", "host", "borrows network capability", true},
  {"std.http.server", "HttpServer", 2, "net", "host", "borrows network capability", true},
  {"std.http.fetch", "HttpResult", 4, "net", "host-runtime", "writes caller response buffer from raw HTTP request envelope", true},
  {"std.http.resultOk", "Bool", 1, "net", "host-runtime", "inspects HTTP result metadata", true},
  {"std.http.resultStatus", "u16", 1, "net", "host-runtime", "reads HTTP status metadata", true},
  {"std.http.resultBodyLen", "usize", 1, "net", "host-runtime", "reads response body length metadata", true},
  {"std.http.resultError", "HttpError", 1, "net", "host-runtime", "reads transport error metadata", true},
  {"std.http.errorNone", "HttpError", 0, "none", "target-neutral", "no allocation", false},
  {"std.http.errorInvalidUrl", "HttpError", 0, "none", "target-neutral", "no allocation", false},
  {"std.http.errorUnsupportedProtocol", "HttpError", 0, "none", "target-neutral", "no allocation", false},
  {"std.http.errorDns", "HttpError", 0, "none", "target-neutral", "no allocation", false},
  {"std.http.errorConnect", "HttpError", 0, "none", "target-neutral", "no allocation", false},
  {"std.http.errorTls", "HttpError", 0, "none", "target-neutral", "no allocation", false},
  {"std.http.errorTimeout", "HttpError", 0, "none", "target-neutral", "no allocation", false},
  {"std.http.errorTooLarge", "HttpError", 0, "none", "target-neutral", "no allocation", false},
  {"std.http.errorProviderUnavailable", "HttpError", 0, "none", "target-neutral", "no allocation", false},
  {"std.http.errorIo", "HttpError", 0, "none", "target-neutral", "no allocation", false},
  {"std.http.errorInvalidRequest", "HttpError", 0, "none", "target-neutral", "no allocation", false},
  {"std.http.responseLen", "usize", 1, "memory", "host-runtime", "reads response bytes written into caller storage", true},
  {"std.http.responseHeadersLen", "usize", 1, "memory", "host-runtime", "reads response header byte length", true},
  {"std.http.responseBodyOffset", "usize", 1, "memory", "host-runtime", "reads body start offset within caller response storage", true},
  {"std.http.headerValue", "HttpHeaderValue", 2, "memory", "host-runtime", "locates a response header value by name", true},
  {"std.http.headerFound", "Bool", 1, "memory", "host-runtime", "inspects header-value metadata", true},
  {"std.http.headerOffset", "usize", 1, "memory", "host-runtime", "reads header-value offset metadata", true},
  {"std.http.headerLen", "usize", 1, "memory", "host-runtime", "reads header-value length metadata", true},
  {"std.http.tlsBoundary", "String", 0, "net", "host", "declares platform-or-C-library TLS boundary", false},
  {"std.fs.host", "Fs", 0, "fs", "host", "no allocation", true},
  {"std.fs.open", "Maybe<owned<File>>", 2, "fs", "host", "owned file handle", true},
  {"std.fs.openOrRaise", "owned<File>", 2, "fs", "host", "owned file handle", true},
  {"std.fs.create", "Maybe<owned<File>>", 2, "fs", "host", "owned file handle", true},
  {"std.fs.createOrRaise", "owned<File>", 2, "fs", "host", "owned file handle", true},
  {"std.fs.read", "usize", 2, "fs", "host", "writes caller buffer", true},
  {"std.fs.readOrRaise", "usize", 2, "fs", "host", "writes caller buffer", true},
  {"std.fs.write", "usize", 2, "fs", "host", "writes bytes to path", true},
  {"std.fs.writeAll", "Bool", 2, "fs", "host", "writes file resource bytes", true},
  {"std.fs.writeAllOrRaise", "Void", 2, "fs", "host", "no allocation", true},
  {"std.fs.fileLenOrRaise", "usize", 1, "fs", "host", "no allocation", true},
  {"std.fs.readAll", "Maybe<owned<ByteBuf>>", 4, "fs", "host", "uses explicit allocator only", true},
  {"std.fs.readAllOrRaise", "owned<ByteBuf>", 4, "fs", "host", "uses explicit allocator only", true},
  {"std.fs.exists", "Bool", 1, "fs", "host", "no allocation", true},
  {"std.fs.readBytes", "Maybe<usize>", 2, "fs", "host", "writes caller buffer", true},
  {"std.fs.writeBytes", "Maybe<usize>", 2, "fs", "host", "no allocation", true},
  {"std.fs.appendBytes", "Maybe<usize>", 2, "fs", "host", "no allocation", true},
  {"std.fs.isDir", "Bool", 1, "fs", "host", "no allocation", true},
  {"std.fs.makeDir", "Bool", 1, "fs", "host", "creates a directory", true},
  {"std.fs.removeDir", "Bool", 1, "fs", "host", "removes a directory", true},
  {"std.fs.remove", "Bool", 1, "fs", "host", "no allocation", true},
  {"std.fs.rename", "Bool", 2, "fs", "host", "no allocation", true},
  {"std.fs.dirEntryCount", "Maybe<usize>", 1, "fs", "host", "directory traversal", true},
  {"std.fs.tempName", "Maybe<String>", 2, "fs", "host", "writes caller buffer", true},
  {"std.fs.atomicWrite", "Bool", 3, "fs", "host", "uses caller-provided temp path", true},
  {"std.fs.fileLen", "Maybe<usize>", 1, "fs", "host", "no allocation", true},
  {"std.fs.close", "Void", 1, "fs", "host", "closes owned file handle", true},
  {NULL, NULL, 0, NULL, NULL, NULL, false},
};

const ZStdHelperInfo *z_std_helper_find(const char *name) {
  if (!name) return NULL;
  for (size_t i = 0; z_std_helpers[i].name; i++) {
    if (strcmp(z_std_helpers[i].name, name) == 0) return &z_std_helpers[i];
  }
  return NULL;
}

int z_std_helper_index(const char *name, size_t max_helpers) {
  if (!name) return -1;
  for (size_t i = 0; z_std_helpers[i].name && i < max_helpers; i++) {
    if (strcmp(z_std_helpers[i].name, name) == 0) return (int)i;
  }
  return -1;
}
