#include "std_sig.h"
#include <stdio.h>
#include <string.h>

const ZStdHelperInfo z_std_helpers[] = {
  {"std.args.len", "usize", 0, {NULL}, {NULL}, "args", "host", "borrows process argv", true, Z_STD_HELPER_KIND_TABLE},
  {"std.args.get", "Maybe<String>", 1, {"usize"}, {NULL}, "args", "host", "borrows process argv", true, Z_STD_HELPER_KIND_TABLE},
  {"std.args.has", "Bool", 1, {"usize"}, {NULL}, "args", "host", "borrows process argv", true, Z_STD_HELPER_KIND_TABLE},
  {"std.args.getOr", "String", 2, {"usize", "String"}, {NULL}, "args", "host", "borrows process argv or fallback", true, Z_STD_HELPER_KIND_TABLE},
  {"std.args.find", "Maybe<usize>", 1, {"String"}, {NULL}, "args", "host", "borrows process argv", true, Z_STD_HELPER_KIND_TABLE},
  {"std.args.valueAfter", "Maybe<String>", 1, {"String"}, {NULL}, "args", "host", "borrows process argv", true, Z_STD_HELPER_KIND_TABLE},
  {"std.args.parseU32", "Maybe<u32>", 1, {"usize"}, {NULL}, "args", "host", "borrows process argv; no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.ascii.digitValue", "Maybe<u8>", 1, {"u8"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.ascii.hexValue", "Maybe<u8>", 1, {"u8"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.ascii.isAlnum", "Bool", 1, {"u8"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.ascii.isAlpha", "Bool", 1, {"u8"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.ascii.isDigit", "Bool", 1, {"u8"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.ascii.isHexDigit", "Bool", 1, {"u8"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.ascii.isLower", "Bool", 1, {"u8"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.ascii.isUpper", "Bool", 1, {"u8"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.ascii.isWhitespace", "Bool", 1, {"u8"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.ascii.toLower", "u8", 1, {"u8"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.ascii.toUpper", "u8", 1, {"u8"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.cli.argEquals", "Bool", 2, {"usize", "String"}, {NULL}, "args", "host", "borrows process argv", true, Z_STD_HELPER_KIND_TABLE},
  {"std.cli.hasFlag", "Bool", 1, {"String"}, {NULL}, "args", "host", "borrows process argv", true, Z_STD_HELPER_KIND_TABLE},
  {"std.cli.optionValue", "Maybe<String>", 1, {"String"}, {NULL}, "args", "host", "borrows process argv", true, Z_STD_HELPER_KIND_TABLE},
  {"std.cli.optionValueOr", "String", 2, {"String", "String"}, {NULL}, "args", "host", "borrows process argv or fallback", true, Z_STD_HELPER_KIND_TABLE},
  {"std.cli.optionU32", "Maybe<u32>", 1, {"String"}, {NULL}, "args", "host", "borrows process argv; no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.cli.successExitCode", "i32", 0, {NULL}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.cli.usageExitCode", "i32", 0, {NULL}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.collections.append", "usize", 3, {"MutSpan<T>", "usize", "Span<T>"}, {NULL}, "memory", "target-neutral", "writes non-overlapping caller storage; returns unchanged length on overflow or invalid length", true, Z_STD_HELPER_KIND_COLLECTIONS_APPEND},
  {"std.collections.contains", "Bool", 3, {"Span<T>", "usize", "T"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_COLLECTIONS_LEN_VALUE},
  {"std.collections.count", "usize", 3, {"Span<T>", "usize", "T"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_COLLECTIONS_LEN_VALUE},
  {"std.collections.moveToFront", "usize", 3, {"MutSpan<T>", "usize", "usize"}, {NULL}, "memory", "target-neutral", "writes caller storage; returns unchanged length for invalid length or index", true, Z_STD_HELPER_KIND_COLLECTIONS_LEN_INDEX},
  {"std.collections.push", "usize", 3, {"MutSpan<T>", "usize", "T"}, {NULL}, "memory", "target-neutral", "writes caller storage; returns unchanged length on overflow", true, Z_STD_HELPER_KIND_COLLECTIONS_PUSH},
  {"std.collections.removeSwap", "usize", 3, {"MutSpan<T>", "usize", "usize"}, {NULL}, "memory", "target-neutral", "writes caller storage; returns unchanged length for invalid length or index", true, Z_STD_HELPER_KIND_COLLECTIONS_LEN_INDEX},
  {"std.collections.view", "Span<T>", 2, {"Span<T>", "usize"}, {NULL}, "memory", "target-neutral", "borrows caller storage prefix", true, Z_STD_HELPER_KIND_COLLECTIONS_VIEW},
  {"std.env.get", "Maybe<String>", 1, {"String"}, {NULL}, "env", "host", "borrows process environment", true, Z_STD_HELPER_KIND_TABLE},
  {"std.env.has", "Bool", 1, {"String"}, {NULL}, "env", "host", "borrows process environment", true, Z_STD_HELPER_KIND_TABLE},
  {"std.env.getOr", "String", 2, {"String", "String"}, {NULL}, "env", "host", "borrows process environment or fallback", true, Z_STD_HELPER_KIND_TABLE},
  {"std.env.parseBool", "Maybe<Bool>", 1, {"String"}, {NULL}, "env", "host", "borrows process environment; no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.env.parseU32", "Maybe<u32>", 1, {"String"}, {NULL}, "env", "host", "borrows process environment; no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fmt.bool", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Bool"}, {NULL}, "memory", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fmt.hexLowerU32", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "u32"}, {NULL}, "memory", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fmt.i32", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "i32"}, {NULL}, "memory", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fmt.u32", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "u32"}, {NULL}, "memory", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fmt.usize", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "usize"}, {NULL}, "memory", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.absI32", "u32", 1, {"i32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.absI64", "u64", 1, {"i64"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.binomialU32", "Maybe<u32>", 2, {"u32", "u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.checkedAddI32", "Maybe<i32>", 2, {"i32", "i32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.checkedAddU32", "Maybe<u32>", 2, {"u32", "u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.checkedAddUsize", "Maybe<usize>", 2, {"usize", "usize"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.checkedLcmU32", "Maybe<u32>", 2, {"u32", "u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.checkedMulI32", "Maybe<i32>", 2, {"i32", "i32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.checkedMulU32", "Maybe<u32>", 2, {"u32", "u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.checkedMulUsize", "Maybe<usize>", 2, {"usize", "usize"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.checkedPowU32", "Maybe<u32>", 2, {"u32", "u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.checkedSubI32", "Maybe<i32>", 2, {"i32", "i32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.checkedSubU32", "Maybe<u32>", 2, {"u32", "u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.checkedSubUsize", "Maybe<usize>", 2, {"usize", "usize"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.clampI32", "i32", 3, {"i32", "i32", "i32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.clampI64", "i64", 3, {"i64", "i64", "i64"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.clampU32", "u32", 3, {"u32", "u32", "u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.clampU64", "u64", 3, {"u64", "u64", "u64"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.clampUsize", "usize", 3, {"usize", "usize", "usize"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.divisorCountU32", "u32", 1, {"u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.factorialU32", "Maybe<u32>", 1, {"u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.gcdU32", "u32", 2, {"u32", "u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.isEvenU32", "Bool", 1, {"u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.isOddU32", "Bool", 1, {"u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.isPrimeU32", "Bool", 1, {"u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.lcmU32", "u32", 2, {"u32", "u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.maxI32", "i32", 2, {"i32", "i32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.maxI64", "i64", 2, {"i64", "i64"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.maxU32", "u32", 2, {"u32", "u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.maxU64", "u64", 2, {"u64", "u64"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.maxUsize", "usize", 2, {"usize", "usize"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.minI32", "i32", 2, {"i32", "i32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.minI64", "i64", 2, {"i64", "i64"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.minU32", "u32", 2, {"u32", "u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.minU64", "u64", 2, {"u64", "u64"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.minUsize", "usize", 2, {"usize", "usize"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.modPowU32", "u32", 3, {"u32", "u32", "u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.powU32", "u32", 2, {"u32", "u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.properDivisorSumU32", "u32", 1, {"u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.saturatingAddI32", "i32", 2, {"i32", "i32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.saturatingAddU32", "u32", 2, {"u32", "u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.saturatingAddUsize", "usize", 2, {"usize", "usize"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.saturatingMulI32", "i32", 2, {"i32", "i32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.saturatingMulU32", "u32", 2, {"u32", "u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.saturatingMulUsize", "usize", 2, {"usize", "usize"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.saturatingSubI32", "i32", 2, {"i32", "i32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.saturatingSubU32", "u32", 2, {"u32", "u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.saturatingSubUsize", "usize", 2, {"usize", "usize"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.math.sqrtFloorU32", "u32", 1, {"u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.path.basename", "String", 1, {"String"}, {NULL}, "path", "target-neutral", "borrows input path", true, Z_STD_HELPER_KIND_TABLE},
  {"std.path.dirname", "String", 1, {"String"}, {NULL}, "path", "target-neutral", "borrows/static path view", true, Z_STD_HELPER_KIND_TABLE},
  {"std.path.extension", "String", 1, {"String"}, {NULL}, "path", "target-neutral", "borrows input path", true, Z_STD_HELPER_KIND_TABLE},
  {"std.path.join", "Maybe<String>", 3, {"MutSpan<u8>", "String", "String"}, {NULL}, "path", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.path.normalize", "Maybe<String>", 2, {"MutSpan<u8>", "String"}, {NULL}, "path", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.path.relative", "Maybe<String>", 3, {"MutSpan<u8>", "String", "String"}, {NULL}, "path", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.search.binaryI32", "usize", 2, {"Span<i32>", "i32"}, {NULL}, "memory", "target-neutral", "no allocation; returns len when absent", true, Z_STD_HELPER_KIND_TABLE},
  {"std.search.binaryU32", "usize", 2, {"Span<u32>", "u32"}, {NULL}, "memory", "target-neutral", "no allocation; returns len when absent", true, Z_STD_HELPER_KIND_TABLE},
  {"std.search.binaryUsize", "usize", 2, {"Span<usize>", "usize"}, {NULL}, "memory", "target-neutral", "no allocation; returns len when absent", true, Z_STD_HELPER_KIND_TABLE},
  {"std.search.indexOf", "usize", 2, {"Span<T>", "T"}, {NULL}, "memory", "target-neutral", "no allocation; returns len when absent", true, Z_STD_HELPER_KIND_SEARCH_INDEX},
  {"std.search.lastIndexOf", "usize", 2, {"Span<T>", "T"}, {NULL}, "memory", "target-neutral", "no allocation; returns len when absent", true, Z_STD_HELPER_KIND_SEARCH_INDEX},
  {"std.search.lowerBoundI32", "usize", 2, {"Span<i32>", "i32"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.search.lowerBoundU32", "usize", 2, {"Span<u32>", "u32"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.search.lowerBoundUsize", "usize", 2, {"Span<usize>", "usize"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.sort.insertionI32", "Void", 1, {"MutSpan<i32>"}, {NULL}, "memory", "target-neutral", "sorts caller storage in place", true, Z_STD_HELPER_KIND_TABLE},
  {"std.sort.insertionU32", "Void", 1, {"MutSpan<u32>"}, {NULL}, "memory", "target-neutral", "sorts caller storage in place", true, Z_STD_HELPER_KIND_TABLE},
  {"std.sort.insertionUsize", "Void", 1, {"MutSpan<usize>"}, {NULL}, "memory", "target-neutral", "sorts caller storage in place", true, Z_STD_HELPER_KIND_TABLE},
  {"std.sort.isSortedI32", "Bool", 1, {"Span<i32>"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.sort.isSortedU32", "Bool", 1, {"Span<u32>"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.sort.isSortedUsize", "Bool", 1, {"Span<usize>"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.str.contains", "Bool", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.str.concat", "Maybe<Span<u8>>", 3, {"MutSpan<u8>", "Span<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.str.copy", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.str.count", "usize", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.str.countByte", "usize", 2, {"Span<u8>", "u8"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.str.eqlIgnoreAsciiCase", "Bool", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.str.endsWith", "Bool", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.str.indexOf", "usize", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "no allocation; returns len when absent", true, Z_STD_HELPER_KIND_TABLE},
  {"std.str.lastIndexOf", "usize", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "no allocation; returns len when absent", true, Z_STD_HELPER_KIND_TABLE},
  {"std.str.repeat", "Maybe<Span<u8>>", 3, {"MutSpan<u8>", "Span<u8>", "usize"}, {NULL}, "memory", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.str.reverse", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes non-overlapping caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.str.startsWith", "Bool", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.str.toLowerAscii", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.str.toUpperAscii", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.str.trimAscii", "Span<u8>", 1, {"Span<u8>"}, {NULL}, "memory", "target-neutral", "borrows input bytes", true, Z_STD_HELPER_KIND_TABLE},
  {"std.str.trimEndAscii", "Span<u8>", 1, {"Span<u8>"}, {NULL}, "memory", "target-neutral", "borrows input bytes", true, Z_STD_HELPER_KIND_TABLE},
  {"std.str.trimStartAscii", "Span<u8>", 1, {"Span<u8>"}, {NULL}, "memory", "target-neutral", "borrows input bytes", true, Z_STD_HELPER_KIND_TABLE},
  {"std.str.wordCountAscii", "usize", 1, {"Span<u8>"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.testing.isTrue", "Bool", 1, {"Bool"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.testing.isFalse", "Bool", 1, {"Bool"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.testing.equalBool", "Bool", 2, {"Bool", "Bool"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.testing.equalUsize", "Bool", 2, {"usize", "usize"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.testing.equalU32", "Bool", 2, {"u32", "u32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.testing.equalI32", "Bool", 2, {"i32", "i32"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.testing.equalBytes", "Bool", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.testing.containsBytes", "Bool", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.testing.startsWith", "Bool", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.testing.endsWith", "Bool", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.text.isAscii", "Bool", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.text.utf8Len", "Maybe<usize>", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.text.utf8Valid", "Bool", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.io.bufferedReader", "BufferedReader", 1, {"MutSpan<u8>"}, {NULL}, "memory", "target-neutral", "uses caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.io.bufferedWriter", "BufferedWriter", 1, {"MutSpan<u8>"}, {NULL}, "memory", "target-neutral", "uses caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.io.readerCapacity", "usize", 1, {"ref<BufferedReader>"}, {NULL}, "memory", "target-neutral", "no allocation", false, Z_STD_HELPER_KIND_TABLE},
  {"std.io.writerCapacity", "usize", 1, {"ref<BufferedWriter>"}, {NULL}, "memory", "target-neutral", "no allocation", false, Z_STD_HELPER_KIND_TABLE},
  {"std.io.copy", "usize", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.io.writeByte", "Maybe<usize>", 3, {"MutSpan<u8>", "usize", "u8"}, {NULL}, "memory", "target-neutral", "writes caller buffer at explicit offset", true, Z_STD_HELPER_KIND_TABLE},
  {"std.io.writeSpan", "Maybe<usize>", 3, {"MutSpan<u8>", "usize", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller buffer at explicit offset", true, Z_STD_HELPER_KIND_TABLE},
  {"std.io.written", "Span<u8>", 2, {"Span<u8>", "usize"}, {NULL}, "memory", "target-neutral", "borrows caller storage prefix", true, Z_STD_HELPER_KIND_TABLE},
  {"std.io.remaining", "usize", 2, {"Span<u8>", "usize"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.io.nextLine", "Maybe<Span<u8>>", 2, {"Span<u8>", "usize"}, {NULL}, "memory", "target-neutral", "borrows one line from input bytes", true, Z_STD_HELPER_KIND_TABLE},
  {"std.io.nextLineStart", "usize", 2, {"Span<u8>", "usize"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.io.countLines", "usize", 1, {"Span<u8>"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.crc32", "u32", 1, {"String"}, {NULL}, "codec", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.crc32Bytes", "u32", 1, {"Span<u8>"}, {NULL}, "codec", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.encodedVarintLen", "usize", 1, {"u32"}, {NULL}, "codec", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.hexDecodedLen", "Maybe<usize>", 1, {"Span<u8>"}, {NULL}, "codec", "target-neutral", "validates hex text without allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.hexDecode", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "codec", "target-neutral", "writes decoded bytes into caller storage", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.base64DecodedLen", "Maybe<usize>", 1, {"Span<u8>"}, {NULL}, "codec", "target-neutral", "validates padded base64 text without allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.base64Decode", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "codec", "target-neutral", "writes decoded bytes into caller storage", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.readU8", "u8", 1, {"String"}, {NULL}, "codec", "target-neutral", "little-endian byte read", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.readU16", "u16", 1, {"String"}, {NULL}, "codec", "target-neutral", "little-endian byte read", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.readU32", "u32", 1, {"String"}, {NULL}, "codec", "target-neutral", "little-endian byte read", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.writeU16", "u32", 1, {"u32"}, {NULL}, "codec", "target-neutral", "little-endian byte write primitive", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.writeU32", "u32", 1, {"u32"}, {NULL}, "codec", "target-neutral", "little-endian byte write primitive", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.readU16Le", "Maybe<u16>", 1, {"Span<u8>"}, {NULL}, "codec", "target-neutral", "bounds-checked little-endian read", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.readU16Be", "Maybe<u16>", 1, {"Span<u8>"}, {NULL}, "codec", "target-neutral", "bounds-checked big-endian read", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.readU32Le", "Maybe<u32>", 1, {"Span<u8>"}, {NULL}, "codec", "target-neutral", "bounds-checked little-endian read", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.readU32Be", "Maybe<u32>", 1, {"Span<u8>"}, {NULL}, "codec", "target-neutral", "bounds-checked big-endian read", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.writeU16Le", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "u16"}, {NULL}, "codec", "target-neutral", "writes little-endian bytes into caller storage", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.writeU16Be", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "u16"}, {NULL}, "codec", "target-neutral", "writes big-endian bytes into caller storage", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.writeU32Le", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "u32"}, {NULL}, "codec", "target-neutral", "writes little-endian bytes into caller storage", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.writeU32Be", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "u32"}, {NULL}, "codec", "target-neutral", "writes big-endian bytes into caller storage", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.varintEncode", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "u32"}, {NULL}, "codec", "target-neutral", "writes unsigned varint bytes into caller storage", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.varintDecode", "Maybe<u32>", 1, {"Span<u8>"}, {NULL}, "codec", "target-neutral", "decodes a bounded unsigned varint without allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.base64EncodedLen", "usize", 1, {"usize"}, {NULL}, "codec", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.base64Encode", "Maybe<String>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "codec", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.hexEncode", "Maybe<String>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "codec", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.utf8Valid", "Bool", 1, {"Span<u8>"}, {NULL}, "codec", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.codec.urlEncode", "Maybe<String>", 2, {"MutSpan<u8>", "String"}, {NULL}, "codec", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.mem.copy", "usize", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.mem.copyItems", "usize", 2, {"MutSpan<T>", "Span<T>"}, {NULL}, "memory", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_MEM_COPY_ITEMS},
  {"std.mem.fill", "usize", 2, {"MutSpan<u8>", "u8"}, {NULL}, "memory", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.mem.fillItems", "usize", 2, {"MutSpan<T>", "T"}, {NULL}, "memory", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_MEM_FILL_ITEMS},
  {"std.mem.eql", "Bool", 2, {"String", "String"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.mem.span", "Span<u8>", 1, {"String"}, {NULL}, "memory", "target-neutral", "borrows input bytes", true, Z_STD_HELPER_KIND_TABLE},
  {"std.mem.contains", "Bool", 2, {"Span<T>", "T"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_MEM_CONTAINS},
  {"std.mem.isEmpty", "Bool", 1, {"Span<T>"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_MEM_IS_EMPTY},
  {"std.mem.prefix", "Span<T>", 2, {"Span<T>", "usize"}, {NULL}, "memory", "target-neutral", "borrows input span", true, Z_STD_HELPER_KIND_MEM_SLICE},
  {"std.mem.dropPrefix", "Span<T>", 2, {"Span<T>", "usize"}, {NULL}, "memory", "target-neutral", "borrows input span", true, Z_STD_HELPER_KIND_MEM_SLICE},
  {"std.mem.len", "usize", 1, {"Span<T>"}, {NULL}, "memory", "target-neutral", "no allocation", false, Z_STD_HELPER_KIND_MEM_LEN},
  {"std.mem.get", "Maybe<T>", 2, {"Span<T>", "usize"}, {NULL}, "memory", "target-neutral", "bounds-checked indexed read", false, Z_STD_HELPER_KIND_MEM_GET},
  {"std.mem.eqlBytes", "Bool", 2, {"Span<T>", "Span<T>"}, {NULL}, "memory", "target-neutral", "no allocation", false, Z_STD_HELPER_KIND_MEM_EQL_BYTES},
  {"std.mem.nullAlloc", "NullAlloc", 0, {NULL}, {NULL}, "alloc", "target-neutral", "never allocates", true, Z_STD_HELPER_KIND_TABLE},
  {"std.mem.fixedBufAlloc", "FixedBufAlloc", 1, {"MutSpan<u8>"}, {NULL}, "alloc", "target-neutral", "uses caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.mem.arena", "FixedBufAlloc", 1, {"MutSpan<u8>"}, {NULL}, "alloc", "target-neutral", "bulk allocation over caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.mem.pageAlloc", "PageAlloc", 0, {NULL}, {NULL}, "alloc", "host", "explicit page allocator handle", false, Z_STD_HELPER_KIND_TABLE},
  {"std.mem.generalAlloc", "GeneralAlloc", 0, {NULL}, {NULL}, "alloc", "host", "explicit general allocator handle", false, Z_STD_HELPER_KIND_TABLE},
  {"std.mem.allocBytes", "Maybe<MutSpan<u8>>", 2, {"Alloc", "usize"}, {NULL}, "alloc", "target-neutral", "uses explicit allocator only", true, Z_STD_HELPER_KIND_MEM_ALLOC_BYTES},
  {"std.mem.byteBuf", "Maybe<owned<ByteBuf>>", 2, {"Alloc", "usize"}, {NULL}, "alloc", "target-neutral", "uses explicit allocator only", true, Z_STD_HELPER_KIND_MEM_BYTE_BUF},
  {"std.mem.vec", "Vec", 1, {"MutSpan<u8>"}, {NULL}, "memory", "target-neutral", "uses caller storage", true, Z_STD_HELPER_KIND_TABLE},
  {"std.mem.vecPush", "Bool", 2, {"mutref<Vec>", "u8"}, {NULL}, "memory", "target-neutral", "writes caller storage", true, Z_STD_HELPER_KIND_TABLE},
  {"std.mem.vecLen", "usize", 1, {"ref<Vec>"}, {NULL}, "memory", "target-neutral", "no allocation", false, Z_STD_HELPER_KIND_TABLE},
  {"std.mem.vecCapacity", "usize", 1, {"ref<Vec>"}, {NULL}, "memory", "target-neutral", "no allocation", false, Z_STD_HELPER_KIND_TABLE},
  {"std.mem.bufBytes", "MutSpan<u8>", 1, {"ref<ByteBuf>"}, {NULL}, "memory", "target-neutral", "borrows owned buffer", false, Z_STD_HELPER_KIND_TABLE},
  {"std.mem.bufLen", "usize", 1, {"ref<ByteBuf>"}, {NULL}, "memory", "target-neutral", "no allocation", false, Z_STD_HELPER_KIND_TABLE},
  {"std.mem.reset", "Void", 1, {"mutref<FixedBufAlloc>"}, {NULL}, "alloc", "target-neutral", "resets explicit allocator", true, Z_STD_HELPER_KIND_TABLE},
  {"std.mem.capacity", "usize", 1, {"FixedBufAlloc"}, {NULL}, "alloc", "target-neutral", "no allocation", false, Z_STD_HELPER_KIND_TABLE},
  {"std.parse.isAsciiDigit", "Bool", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.parse.isAsciiAlpha", "Bool", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.parse.isIdentifierStart", "Bool", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.parse.isWhitespace", "Bool", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.parse.scanDigits", "usize", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.parse.scanIdentifier", "usize", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.parse.scanUntilByte", "usize", 2, {"Span<u8>", "u8"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.parse.scanWhitespace", "usize", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.parse.tokenAscii", "Span<u8>", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "borrows input token", true, Z_STD_HELPER_KIND_TABLE},
  {"std.parse.parseBool", "Maybe<Bool>", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.parse.parseI32", "Maybe<i32>", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.parse.parseU8", "Maybe<u8>", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.parse.parseU16", "Maybe<u16>", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.parse.parseU32", "Maybe<u32>", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.parse.parseUsize", "Maybe<usize>", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.json.validate", "Bool", 1, {"String"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.json.validateBytes", "Bool", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.json.parse", "Maybe<JsonDoc>", 2, {"Alloc", "String"}, {NULL}, "alloc", "target-neutral", "uses explicit allocator only", true, Z_STD_HELPER_KIND_JSON_PARSE},
  {"std.json.parseBytes", "Maybe<JsonDoc>", 2, {"Alloc", "Span<u8>"}, {NULL}, "alloc", "target-neutral", "uses explicit allocator only", true, Z_STD_HELPER_KIND_JSON_PARSE_BYTES},
  {"std.json.streamTokens", "usize", 1, {"String"}, {NULL}, "parse", "target-neutral", "streaming token count", true, Z_STD_HELPER_KIND_TABLE},
  {"std.json.streamTokensBytes", "usize", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "streaming token count", true, Z_STD_HELPER_KIND_TABLE},
  {"std.json.writeString", "Maybe<String>", 2, {"MutSpan<u8>", "String"}, {NULL}, "parse", "target-neutral", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.json.decodeBoundary", "String", 0, {NULL}, {NULL}, "parse", "target-neutral", "typed decode boundary metadata", false, Z_STD_HELPER_KIND_TABLE},
  {"std.json.errorNone", "u32", 0, {NULL}, {NULL}, "parse", "target-neutral", "structured validation status code", true, Z_STD_HELPER_KIND_TABLE},
  {"std.json.errorInvalid", "u32", 0, {NULL}, {NULL}, "parse", "target-neutral", "structured validation status code", true, Z_STD_HELPER_KIND_TABLE},
  {"std.json.errorTrailing", "u32", 0, {NULL}, {NULL}, "parse", "target-neutral", "structured validation status code", true, Z_STD_HELPER_KIND_TABLE},
  {"std.json.validateError", "u32", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "returns structured validation status without allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.json.field", "Maybe<Span<u8>>", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "returns a raw top-level object field value slice", true, Z_STD_HELPER_KIND_TABLE},
  {"std.json.stringDecode", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "decodes a JSON string value into caller storage", true, Z_STD_HELPER_KIND_TABLE},
  {"std.json.string", "Maybe<Span<u8>>", 3, {"MutSpan<u8>", "Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "looks up and decodes a top-level string field", true, Z_STD_HELPER_KIND_TABLE},
  {"std.json.u32", "Maybe<u32>", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "looks up and decodes a top-level unsigned integer field", true, Z_STD_HELPER_KIND_TABLE},
  {"std.json.bool", "Maybe<Bool>", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "looks up and decodes a top-level bool field", true, Z_STD_HELPER_KIND_TABLE},
  {"std.json.writeStringBytes", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "writes an escaped JSON string into caller storage", true, Z_STD_HELPER_KIND_TABLE},
  {"std.json.writeObject1String", "Maybe<Span<u8>>", 3, {"MutSpan<u8>", "Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "writes a one-field object with a string value", true, Z_STD_HELPER_KIND_TABLE},
  {"std.json.writeObject1U32", "Maybe<Span<u8>>", 3, {"MutSpan<u8>", "Span<u8>", "u32"}, {NULL}, "parse", "target-neutral", "writes a one-field object with an unsigned integer value", true, Z_STD_HELPER_KIND_TABLE},
  {"std.json.writeObject1Bool", "Maybe<Span<u8>>", 3, {"MutSpan<u8>", "Span<u8>", "Bool"}, {NULL}, "parse", "target-neutral", "writes a one-field object with a bool value", true, Z_STD_HELPER_KIND_TABLE},
  {"std.toml.validate", "Bool", 1, {"String"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.toml.validateBytes", "Bool", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.toml.field", "Maybe<Span<u8>>", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "returns a raw top-level or dotted table field value slice", true, Z_STD_HELPER_KIND_TABLE},
  {"std.toml.stringDecode", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "decodes a TOML basic string value into caller storage", true, Z_STD_HELPER_KIND_TABLE},
  {"std.toml.string", "Maybe<Span<u8>>", 3, {"MutSpan<u8>", "Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "looks up and decodes a string field", true, Z_STD_HELPER_KIND_TABLE},
  {"std.toml.u32", "Maybe<u32>", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "looks up and decodes an unsigned integer field", true, Z_STD_HELPER_KIND_TABLE},
  {"std.toml.bool", "Maybe<Bool>", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "looks up and decodes a bool field", true, Z_STD_HELPER_KIND_TABLE},
  {"std.log.message", "Maybe<Span<u8>>", 3, {"MutSpan<u8>", "Span<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller buffer with one JSON Lines record", true, Z_STD_HELPER_KIND_TABLE},
  {"std.log.keyValue", "Maybe<Span<u8>>", 4, {"MutSpan<u8>", "Span<u8>", "Span<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller buffer with one JSON Lines key-value record", true, Z_STD_HELPER_KIND_TABLE},
  {"std.url.percentEncode", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "percent-encodes bytes into caller storage", true, Z_STD_HELPER_KIND_TABLE},
  {"std.url.percentDecode", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "percent-decodes bytes into caller storage", true, Z_STD_HELPER_KIND_TABLE},
  {"std.url.queryEscape", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "query-escapes bytes into caller storage", true, Z_STD_HELPER_KIND_TABLE},
  {"std.url.queryUnescape", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "query-unescapes bytes into caller storage", true, Z_STD_HELPER_KIND_TABLE},
  {"std.url.scheme", "Maybe<Span<u8>>", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "borrows the URL scheme if present", true, Z_STD_HELPER_KIND_TABLE},
  {"std.url.authority", "Maybe<Span<u8>>", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "borrows the URL authority if present", true, Z_STD_HELPER_KIND_TABLE},
  {"std.url.host", "Maybe<Span<u8>>", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "borrows the URL host if present", true, Z_STD_HELPER_KIND_TABLE},
  {"std.url.path", "Span<u8>", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "borrows the URL path or an empty suffix", true, Z_STD_HELPER_KIND_TABLE},
  {"std.url.query", "Maybe<Span<u8>>", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "borrows the URL query string if present", true, Z_STD_HELPER_KIND_TABLE},
  {"std.url.queryValue", "Maybe<Span<u8>>", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "borrows a raw query parameter value by key", true, Z_STD_HELPER_KIND_TABLE},
  {"std.url.writeQueryParam", "Maybe<Span<u8>>", 3, {"MutSpan<u8>", "Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "writes an escaped key=value query parameter", true, Z_STD_HELPER_KIND_TABLE},
  {"std.url.appendQuery", "Maybe<Span<u8>>", 3, {"MutSpan<u8>", "Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "writes a URL with an appended raw query segment", true, Z_STD_HELPER_KIND_TABLE},
  {"std.time.ns", "Duration", 1, {"i64"}, {NULL}, "time", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.time.us", "Duration", 1, {"i64"}, {NULL}, "time", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.time.ms", "Duration", 1, {"i32"}, {NULL}, "time", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.time.seconds", "Duration", 1, {"i32"}, {NULL}, "time", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.time.minutes", "Duration", 1, {"i32"}, {NULL}, "time", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.time.hours", "Duration", 1, {"i32"}, {NULL}, "time", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.time.zero", "Duration", 0, {NULL}, {NULL}, "time", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.time.add", "Duration", 2, {"Duration", "Duration"}, {NULL}, "time", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.time.monotonic", "Duration", 0, {NULL}, {NULL}, "time", "host", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.time.wallSeconds", "i64", 0, {NULL}, {NULL}, "time", "host", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.time.sub", "Duration", 2, {"Duration", "Duration"}, {NULL}, "time", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.time.asNs", "i64", 1, {"Duration"}, {NULL}, "time", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.time.asUsFloor", "i64", 1, {"Duration"}, {NULL}, "time", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.time.asMsFloor", "i32", 1, {"Duration"}, {NULL}, "time", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.time.asSecondsFloor", "i64", 1, {"Duration"}, {NULL}, "time", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.time.min", "Duration", 2, {"Duration", "Duration"}, {NULL}, "time", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.time.max", "Duration", 2, {"Duration", "Duration"}, {NULL}, "time", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.time.clamp", "Duration", 3, {"Duration", "Duration", "Duration"}, {NULL}, "time", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.time.lessThan", "Bool", 2, {"Duration", "Duration"}, {NULL}, "time", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.time.isZero", "Bool", 1, {"Duration"}, {NULL}, "time", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.rand.seed", "RandSource", 1, {"u32"}, {NULL}, "rand", "target-neutral", "deterministic test source", true, Z_STD_HELPER_KIND_TABLE},
  {"std.rand.nextU32", "u32", 1, {"mutref<RandSource>"}, {NULL}, "rand", "target-neutral", "updates explicit source", true, Z_STD_HELPER_KIND_TABLE},
  {"std.rand.nextBool", "Bool", 1, {"mutref<RandSource>"}, {NULL}, "rand", "target-neutral", "updates explicit source", true, Z_STD_HELPER_KIND_TABLE},
  {"std.rand.entropyU32", "u32", 0, {NULL}, {NULL}, "rand", "host", "target entropy source", true, Z_STD_HELPER_KIND_TABLE},
  {"std.rand.entropySeed", "RandSource", 0, {NULL}, {NULL}, "rand", "host", "target entropy source", true, Z_STD_HELPER_KIND_TABLE},
  {"std.proc.spawn", "ProcStatus", 1, {"String"}, {NULL}, "proc", "host", "explicit process capability", true, Z_STD_HELPER_KIND_TABLE},
  {"std.proc.exitCode", "i32", 1, {"ProcStatus"}, {NULL}, "proc", "host", "no allocation", false, Z_STD_HELPER_KIND_TABLE},
  {"std.proc.succeeded", "Bool", 1, {"ProcStatus"}, {NULL}, "proc", "host", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.proc.failed", "Bool", 1, {"ProcStatus"}, {NULL}, "proc", "host", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.crypto.hash32", "u32", 1, {"Span<u8>"}, {NULL}, "codec", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.crypto.hmac32", "u32", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "codec", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.crypto.constantTimeEql", "Bool", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.crypto.secureRandomU32", "u32", 0, {NULL}, {NULL}, "rand", "host", "target entropy source", true, Z_STD_HELPER_KIND_TABLE},
  {"std.net.host", "Net", 0, {NULL}, {NULL}, "net", "host", "explicit network capability handle", false, Z_STD_HELPER_KIND_TABLE},
  {"std.net.address", "Address", 2, {"String", "u16"}, {NULL}, "net", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.net.dnsName", "String", 1, {"Address"}, {NULL}, "net", "target-neutral", "borrows address host", false, Z_STD_HELPER_KIND_TABLE},
  {"std.net.connect", "Maybe<Conn>", 2, {"Net", "Address"}, {NULL}, "net", "host", "no allocation; returns unopened bootstrap handle", true, Z_STD_HELPER_KIND_TABLE},
  {"std.net.listen", "Maybe<Listener>", 2, {"Net", "Address"}, {NULL}, "net", "host", "no allocation; returns unopened bootstrap handle", true, Z_STD_HELPER_KIND_TABLE},
  {"std.net.withTimeout", "Address", 2, {"Address", "Duration"}, {NULL}, "net", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.net.localhost", "Address", 1, {"u16"}, {NULL}, "net", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.net.loopback", "Address", 1, {"u16"}, {NULL}, "net", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.parseMethod", "HttpMethod", 1, {"String"}, {NULL}, "parse", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.client", "HttpClient", 1, {"Net"}, {NULL}, "net", "host", "borrows network capability", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.server", "HttpServer", 2, {"Net", "Address"}, {NULL}, "net", "host", "borrows network capability", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.fetch", "HttpResult", 4, {"HttpClient", "Span<u8>", "MutSpan<u8>", "Duration"}, {NULL}, "net", "host-runtime", "writes caller response buffer from raw HTTP request envelope", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.resultOk", "Bool", 1, {"HttpResult"}, {NULL}, "net", "host-runtime", "inspects HTTP result metadata", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.resultStatus", "u16", 1, {"HttpResult"}, {NULL}, "net", "host-runtime", "reads HTTP status metadata", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.resultBodyLen", "usize", 1, {"HttpResult"}, {NULL}, "net", "host-runtime", "reads response body length metadata", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.resultError", "HttpError", 1, {"HttpResult"}, {NULL}, "net", "host-runtime", "reads transport error metadata", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.errorNone", "HttpError", 0, {NULL}, {NULL}, "none", "target-neutral", "no allocation", false, Z_STD_HELPER_KIND_TABLE},
  {"std.http.errorInvalidUrl", "HttpError", 0, {NULL}, {NULL}, "none", "target-neutral", "no allocation", false, Z_STD_HELPER_KIND_TABLE},
  {"std.http.errorUnsupportedProtocol", "HttpError", 0, {NULL}, {NULL}, "none", "target-neutral", "no allocation", false, Z_STD_HELPER_KIND_TABLE},
  {"std.http.errorDns", "HttpError", 0, {NULL}, {NULL}, "none", "target-neutral", "no allocation", false, Z_STD_HELPER_KIND_TABLE},
  {"std.http.errorConnect", "HttpError", 0, {NULL}, {NULL}, "none", "target-neutral", "no allocation", false, Z_STD_HELPER_KIND_TABLE},
  {"std.http.errorTls", "HttpError", 0, {NULL}, {NULL}, "none", "target-neutral", "no allocation", false, Z_STD_HELPER_KIND_TABLE},
  {"std.http.errorTimeout", "HttpError", 0, {NULL}, {NULL}, "none", "target-neutral", "no allocation", false, Z_STD_HELPER_KIND_TABLE},
  {"std.http.errorTooLarge", "HttpError", 0, {NULL}, {NULL}, "none", "target-neutral", "no allocation", false, Z_STD_HELPER_KIND_TABLE},
  {"std.http.errorProviderUnavailable", "HttpError", 0, {NULL}, {NULL}, "none", "target-neutral", "no allocation", false, Z_STD_HELPER_KIND_TABLE},
  {"std.http.errorIo", "HttpError", 0, {NULL}, {NULL}, "none", "target-neutral", "no allocation", false, Z_STD_HELPER_KIND_TABLE},
  {"std.http.errorInvalidRequest", "HttpError", 0, {NULL}, {NULL}, "none", "target-neutral", "no allocation", false, Z_STD_HELPER_KIND_TABLE},
  {"std.http.responseLen", "usize", 1, {"Span<u8>"}, {NULL}, "memory", "host-runtime", "reads response bytes written into caller storage", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.responseHeadersLen", "usize", 1, {"Span<u8>"}, {NULL}, "memory", "host-runtime", "reads response header byte length", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.responseBodyOffset", "usize", 1, {"Span<u8>"}, {NULL}, "memory", "host-runtime", "reads body start offset within caller response storage", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.headerValue", "HttpHeaderValue", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "memory", "host-runtime", "locates a response header value by name", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.headerFound", "Bool", 1, {"HttpHeaderValue"}, {NULL}, "memory", "host-runtime", "inspects header-value metadata", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.headerOffset", "usize", 1, {"HttpHeaderValue"}, {NULL}, "memory", "host-runtime", "reads header-value offset metadata", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.headerLen", "usize", 1, {"HttpHeaderValue"}, {NULL}, "memory", "host-runtime", "reads header-value length metadata", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.tlsBoundary", "String", 0, {NULL}, {NULL}, "net", "host", "declares platform-or-C-library TLS boundary", false, Z_STD_HELPER_KIND_TABLE},
  {"std.http.statusReason", "String", 1, {"u16"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.statusIsInformational", "Bool", 1, {"u16"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.statusIsSuccess", "Bool", 1, {"u16"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.statusIsRedirect", "Bool", 1, {"u16"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.statusIsClientError", "Bool", 1, {"u16"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.statusIsServerError", "Bool", 1, {"u16"}, {NULL}, "none", "target-neutral", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.writeRequest", "Maybe<Span<u8>>", 3, {"MutSpan<u8>", "Span<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller request buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.writeJsonRequest", "Maybe<Span<u8>>", 3, {"MutSpan<u8>", "Span<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller request buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.writeResponse", "Maybe<Span<u8>>", 3, {"MutSpan<u8>", "u16", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller response buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.writeJsonResponse", "Maybe<Span<u8>>", 3, {"MutSpan<u8>", "u16", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller response buffer", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.writeCorsPreflight", "Maybe<Span<u8>>", 4, {"MutSpan<u8>", "Span<u8>", "Span<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes a 204 CORS preflight response", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.writeCorsJsonResponse", "Maybe<Span<u8>>", 4, {"MutSpan<u8>", "Span<u8>", "Span<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes a JSON response with Access-Control-Allow-Origin", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.writeJsonOk", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller response buffer with 200 JSON status", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.writeJsonCreated", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller response buffer with 201 JSON status", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.writeJsonBadRequest", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller response buffer with 400 JSON status", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.writeJsonUnauthorized", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller response buffer with 401 JSON status", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.writeJsonForbidden", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller response buffer with 403 JSON status", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.writeJsonNotFound", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller response buffer with 404 JSON status", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.writeJsonMethodNotAllowed", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller response buffer with 405 JSON status", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.writeJsonConflict", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller response buffer with 409 JSON status", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.writeJsonUnprocessable", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller response buffer with 422 JSON status", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.writeJsonTooManyRequests", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller response buffer with 429 JSON status", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.writeJsonInternalServerError", "Maybe<Span<u8>>", 2, {"MutSpan<u8>", "Span<u8>"}, {NULL}, "memory", "target-neutral", "writes caller response buffer with 500 JSON status", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.writeNoContent", "Maybe<Span<u8>>", 1, {"MutSpan<u8>"}, {NULL}, "memory", "target-neutral", "writes caller response buffer with 204 status and empty body", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.requestMethodName", "Maybe<Span<u8>>", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "borrows request envelope", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.requestTarget", "Maybe<Span<u8>>", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "borrows request envelope", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.requestPath", "Maybe<Span<u8>>", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "borrows request envelope", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.requestQuery", "Maybe<Span<u8>>", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "borrows request envelope", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.requestQueryValue", "Maybe<Span<u8>>", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "borrows request envelope", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.requestHeader", "Maybe<Span<u8>>", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "borrows request envelope", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.requestBearerToken", "Maybe<Span<u8>>", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "borrows bearer token from Authorization header", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.requestCookie", "Maybe<Span<u8>>", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "borrows named cookie value from Cookie header", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.requestBody", "Maybe<Span<u8>>", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "borrows request envelope", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.requestBodyWithin", "Maybe<Span<u8>>", 2, {"Span<u8>", "usize"}, {NULL}, "parse", "target-neutral", "borrows request envelope", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.requestHasJsonContentType", "Bool", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "checks for application/json content type", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.requestJsonBodyWithin", "Maybe<Span<u8>>", 2, {"Span<u8>", "usize"}, {NULL}, "parse", "target-neutral", "borrows validated JSON request body within size limit", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.requestMatches", "Bool", 3, {"Span<u8>", "Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "borrows request envelope", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.requestMethodIs", "Bool", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "matches a request method", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.requestIsGet", "Bool", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "matches GET and normalized path", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.requestIsHead", "Bool", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "matches HEAD and normalized path", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.requestIsOptions", "Bool", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "matches OPTIONS and normalized path", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.requestIsPost", "Bool", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "matches POST and normalized path", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.requestIsPut", "Bool", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "matches PUT and normalized path", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.requestIsPatch", "Bool", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "matches PATCH and normalized path", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.requestIsDelete", "Bool", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "matches DELETE and normalized path", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.pathSegmentCount", "usize", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "counts non-empty path segments", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.pathSegment", "Maybe<Span<u8>>", 2, {"Span<u8>", "usize"}, {NULL}, "parse", "target-neutral", "borrows a non-empty path segment by zero-based index", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.requestPathSegmentCount", "usize", 1, {"Span<u8>"}, {NULL}, "parse", "target-neutral", "counts non-empty normalized request path segments", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.requestPathSegment", "Maybe<Span<u8>>", 2, {"Span<u8>", "usize"}, {NULL}, "parse", "target-neutral", "borrows a normalized request path segment by zero-based index", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.requestPathStartsWith", "Bool", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "checks normalized path prefix", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.requestPathTailAfter", "Maybe<Span<u8>>", 2, {"Span<u8>", "Span<u8>"}, {NULL}, "parse", "target-neutral", "borrows normalized path tail after prefix", true, Z_STD_HELPER_KIND_TABLE},
  {"std.http.headerBytes", "Maybe<Span<u8>>", 2, {"Span<u8>", "HttpHeaderValue"}, {NULL}, "memory", "host-runtime", "borrows response header value bytes", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.responseBody", "Maybe<Span<u8>>", 2, {"Span<u8>", "HttpResult"}, {NULL}, "memory", "host-runtime", "borrows response body bytes", true, Z_STD_HELPER_KIND_TABLE}, {"std.http.responseBodyBytes", "Maybe<Span<u8>>", 1, {"Span<u8>"}, {NULL}, "memory", "target-neutral", "borrows body bytes from a local response envelope", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.host", "Fs", 0, {NULL}, {NULL}, "fs", "host", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.open", "Maybe<owned<File>>", 2, {"Fs", "String"}, {NULL}, "fs", "host", "owned file handle", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.openOrRaise", "owned<File>", 2, {"Fs", "String"}, {"NotFound", "TooLarge", "Io"}, "fs", "host", "owned file handle", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.create", "Maybe<owned<File>>", 2, {"Fs", "String"}, {NULL}, "fs", "host", "owned file handle", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.createOrRaise", "owned<File>", 2, {"Fs", "String"}, {"NotFound", "TooLarge", "Io"}, "fs", "host", "owned file handle", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.read", "usize", 2, {"String", "MutSpan<u8>"}, {NULL}, "fs", "host", "writes caller buffer", true, Z_STD_HELPER_KIND_FS_READ},
  {"std.fs.readOrRaise", "usize", 2, {"mutref<File>", "MutSpan<u8>"}, {"NotFound", "TooLarge", "Io"}, "fs", "host", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.write", "usize", 2, {"String", "String"}, {NULL}, "fs", "host", "writes bytes to path", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.writeAll", "Bool", 2, {"mutref<File>", "Span<u8>"}, {NULL}, "fs", "host", "writes file resource bytes", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.writeAllOrRaise", "Void", 2, {"mutref<File>", "Span<u8>"}, {"NotFound", "TooLarge", "Io"}, "fs", "host", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.fileLenOrRaise", "usize", 1, {"mutref<File>"}, {"NotFound", "TooLarge", "Io"}, "fs", "host", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.readAll", "Maybe<owned<ByteBuf>>", 4, {"Alloc", "Fs", "String", "usize"}, {NULL}, "fs", "host", "uses explicit allocator only", true, Z_STD_HELPER_KIND_FS_READ_ALL},
  {"std.fs.readAllOrRaise", "owned<ByteBuf>", 4, {"Alloc", "Fs", "String", "usize"}, {"NotFound", "TooLarge", "Io"}, "fs", "host", "uses explicit allocator only", true, Z_STD_HELPER_KIND_FS_READ_ALL_OR_RAISE},
  {"std.fs.exists", "Bool", 1, {"String"}, {NULL}, "fs", "host", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.readBytes", "Maybe<usize>", 2, {"String", "MutSpan<u8>"}, {NULL}, "fs", "host", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.writeBytes", "Maybe<usize>", 2, {"String", "Span<u8>"}, {NULL}, "fs", "host", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.isDir", "Bool", 1, {"String"}, {NULL}, "fs", "host", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.makeDir", "Bool", 1, {"String"}, {NULL}, "fs", "host", "creates a directory", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.removeDir", "Bool", 1, {"String"}, {NULL}, "fs", "host", "removes a directory", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.remove", "Bool", 1, {"String"}, {NULL}, "fs", "host", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.rename", "Bool", 2, {"String", "String"}, {NULL}, "fs", "host", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.dirEntryCount", "Maybe<usize>", 1, {"String"}, {NULL}, "fs", "host", "directory traversal", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.tempName", "Maybe<String>", 2, {"MutSpan<u8>", "String"}, {NULL}, "fs", "host", "writes caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.atomicWrite", "Bool", 3, {"String", "String", "Span<u8>"}, {NULL}, "fs", "host", "uses caller-provided temp path", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.fileLen", "Maybe<usize>", 1, {"mutref<File>"}, {NULL}, "fs", "host", "no allocation", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.close", "Void", 1, {"mutref<File>"}, {NULL}, "fs", "host", "closes owned file handle", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.readFile", "Maybe<usize>", 3, {"Fs", "String", "MutSpan<u8>"}, {NULL}, "fs", "host", "reads full file into caller buffer through explicit Fs; null when too large", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.writeFile", "Bool", 3, {"Fs", "String", "Span<u8>"}, {NULL}, "fs", "host", "writes bytes through explicit Fs", true, Z_STD_HELPER_KIND_TABLE},
  {"std.fs.copyFile", "Bool", 3, {"String", "String", "MutSpan<u8>"}, {NULL}, "fs", "host", "copies through caller buffer", true, Z_STD_HELPER_KIND_TABLE},
  {NULL, NULL, 0, {NULL}, {NULL}, NULL, NULL, NULL, false, Z_STD_HELPER_KIND_TABLE},
};

size_t z_std_helper_count(void) {
  size_t count = 0;
  while (z_std_helpers[count].name) count++;
  return count;
}

const ZStdHelperInfo *z_std_helper_find(const char *name) {
  if (!name) return NULL;
  for (size_t i = 0; z_std_helpers[i].name; i++) {
    if (strcmp(z_std_helpers[i].name, name) == 0) return &z_std_helpers[i];
  }
  return NULL;
}

const char *z_std_helper_arg_type(const char *name, size_t index) {
  if (index >= Z_STD_HELPER_MAX_ARGS) return NULL;
  const ZStdHelperInfo *helper = z_std_helper_find(name);
  return helper ? helper->arg_types[index] : NULL;
}

const char *z_std_helper_error_name(const ZStdHelperInfo *helper, size_t index) {
  if (!helper || index >= Z_STD_HELPER_MAX_ERRORS) return NULL;
  return helper->error_names[index];
}

bool z_std_helper_is_fallible(const ZStdHelperInfo *helper) {
  return z_std_helper_error_name(helper, 0) != NULL;
}

void z_std_helper_error_set_text(const ZStdHelperInfo *helper, char *buf, size_t cap) {
  if (!buf || cap == 0) return;
  snprintf(buf, cap, "raises [");
  size_t used = strlen(buf);
  bool first = true;
  for (size_t i = 0; i < Z_STD_HELPER_MAX_ERRORS; i++) {
    const char *error_name = z_std_helper_error_name(helper, i);
    if (!error_name) break;
    if (used >= cap - 1) break;
    snprintf(buf + used, cap - used, "%s%s", first ? "" : ", ", error_name);
    used = strlen(buf);
    first = false;
  }
  if (used < cap - 1) snprintf(buf + used, cap - used, "]");
  else buf[cap - 1] = '\0';
}

int z_std_helper_index(const char *name, size_t max_helpers) {
  if (!name) return -1;
  for (size_t i = 0; z_std_helpers[i].name && i < max_helpers; i++) {
    if (strcmp(z_std_helpers[i].name, name) == 0) return (int)i;
  }
  return -1;
}

ZStdHelperKind z_std_helper_kind(const ZStdHelperInfo *helper) {
  return helper ? helper->kind : Z_STD_HELPER_KIND_UNKNOWN;
}
